/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as AnimeAnimeIdImport } from "./routes/anime.$animeId";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const IndexRoute = IndexImport.update({
	path: "/",
	getParentRoute: () => rootRoute,
} as any);

const AnimeAnimeIdRoute = AnimeAnimeIdImport.update({
	path: "/anime/$animeId",
	getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexImport;
			parentRoute: typeof rootRoute;
		};
		"/anime/$animeId": {
			id: "/anime/$animeId";
			path: "/anime/$animeId";
			fullPath: "/anime/$animeId";
			preLoaderRoute: typeof AnimeAnimeIdImport;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
	IndexRoute,
	AnimeAnimeIdRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.ts",
      "children": [
        "/",
        "/anime/$animeId"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/anime/$animeId": {
      "filePath": "anime.$animeId.ts"
    }
  }
}
ROUTE_MANIFEST_END */
